### ISSUE TITLE
Craft 4 compatible

### ISSUE THREAD

**Issue by ruudvdboom** [verbb/kint#5]
Hi, 

Are there any plans to update the plugin so it's compatible with Craft 4?

Cheers

**Comment by jamesmacwhite** [comment]
I'd like to ask the same, however there has been a lack of updates since the Craft CMS 3 port, it's possibly unlikely that it will be. Depending on how much effort, I may make a fork of it, as I also use it in another project I manage.

**Comment by jamesmacwhite** [comment]
It doesn't need too much to convert it to Craft CMS 4. Here's a branch with the updated Craft CMS 4 code:

https://github.com/nottinghamcollege/craft-kint/tree/craft4

Mostly, type casting, couple of class name changes and that's about it.

I'd submit it as a pull request, but I don't think the author is active currently, but if you want you can test it out. You'll have to override composer with a repositories definition to point to the the forked version not the published version, but it's still using the same namespace.

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3) as a few people have requested it.

If you're looking for a new home for Kint, we'd be happy to continue development at Verbb (including updating to Craft 4) - but just let us know if you've got plans to continue things and update to Craft 4! @mildlygeeky

**Comment by mildlygeeky** [comment]
Hey Josh! Happy to transfer the project over to verbb, for sure. I’ve mostly become a xDebug guy, and really don’t use this anymore.
________________________________

**Comment by jamesmacwhite** [comment]
@mildlygeeky Thanks for for confirming the status of the plugin.

@engram-design Awesome, you are considering adding it to Verbb's migration project. I had a look at the Craft CMS 4 feasibility yesterday and create a fork, this runs on Craft CMS 4: https://github.com/nottinghamcollege/craft-kint/tree/craft4. TO get to it run doesn't need much.

My general observations are:

* Several dependency bumps are needed to get it to work on Craft CMS 4, particularly kint-php/kint-twig.
* Usual typecasting is needed in places.
* The Twig extension needs a couple of class changes.
* kint-js is no longer maintained and only supports Kint 3.x. The `j('data')` function is the main functionality affected by this.
* The plugin could be upgraded to use Kint 4, but you then lose the dumping to JS with `j('data')`, unless an kint-js alternative is developed

**Comment by engram-design** [comment]
@mildlygeeky Happy to take it on, maybe we catch up over Discord? (@crawf). I'm also not really using Kint due to other alternatives out there, but happy to help out the people who would like to keep using it.

@jamesmacwhite We probably want to update to Kint 4 to be on the latest and greatest. Particularly as they add support for PHP 8.1, so sorry to say, but I think we need to lose the `j()` function for Craft 4.

**Comment by mikesnoeren** [comment]
It's been over three months since this issue has been created, have there been any updates on this?
This is currently the only plugin we use that hasn't been ported to Craft 4.

About the `j()` function: I wasn't even aware of it's existence.

**Comment by engram-design** [comment]
@mikesnoeren Sorry for the delay, we did only inherit this a month ago, and we've been waiting on some other plugins to be transferred to us to upgrade at the same time (for efficiency), but we'll likely just jump on this plugin and update it next week.

**Comment by mikesnoeren** [comment]
@engram-design Good to hear the plugin is getting updated soon. Appreciate it!

**Comment by jamesmacwhite** [comment]
@mikesnoeren There is a branch on a fork that I tested with Craft 4, you can use it temporarily until an official version is released here if you need it. It uses a slightly older version of Kint and may not support PHP 8 though.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/kint/releases/tag/3.0.0)
