### ISSUE TITLE
Built in config files

### ISSUE THREAD

**Issue by mikesnoeren** [verbb/kint#6]
### What are you trying to do?

Add config files for Kint settings. 
We currently do it this way, which doesn't align with all our other configurations:

```php
<?php
if (!class_exists('Kint\Renderer\RichRenderer')) {
    return;
}

// Kint\Kint::$max_depth = 4; // <- this doesn't work in the verbb version anymore, can this be fixed too? :)
Kint\Renderer\RichRenderer::$folder = true;
```

### What's your proposed solution?

Add a settings php file so we can give the plugin an array with settings

**Comment by engram-design** [comment]
Added `kintSettings` and `richRendererSettings` plugin settings to control this. Refer to the [docs](https://github.com/verbb/kint#configuration). [3.1.0](https://github.com/verbb/kint/releases/tag/3.1.0)

By the way, looks like Kint has [changed `$max_depth`](https://github.com/kint-php/kint/issues/374#issuecomment-997179589)

**Comment by mikesnoeren** [comment]
Thanks for the quick fix @engram-design, much appreciated!
